@IMSApplication.API_HostAddress = http://localhost:5262

GET {{IMSApplication.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{IMSApplication.API_HostAddress}}/api/users
Content-Type: application/json

{
  "FullName" : "Nimesh",
  "Email" : "nims@gmail.com",
  "City" : "Mumbai"
}

###

POST {{IMSApplication.API_HostAddress}}/api/products
Content-Type: application/json

{
  //Products
}

###

POST {{IMSApplication.API_HostAddress}}/api/orderdetails
Content-Type: application/json

{
  //OrderDetail
}

###
